### ISSUE TITLE
Asking for pretrained model

### ISSUE THREAD

**Issue by ZhangYuef** [RyanXingQL/PowerQE#3]
Hi, thanks for sharing! I am wondering if you could offer pretrained models for reproducing the results. If so, when could them be available?

**Comment by ryanxingql** [comment]
Hi
Yes, I will release the pre-trained models soon.
I'm still conducting training and IQA, since the DIV2K images are too big and thus the training and IQA are somehow time-consuming.

v1 provides the pre-trained models trained at down-sampled DIV2K images. You can obtain those models at [Release](https://github.com/RyanXingQL/PowerQE/releases). 
See also [v1 Instruction](https://github.com/RyanXingQL/PowerQE/tree/ea903fd0d04154c95b321b5100540249856bd44b).

**Comment by ZhangYuef** [comment]
> Hi
> Yes, I will release the pre-trained models soon.
> I'm still conducting training and IQA, since the DIV2K images are too big and thus the training and IQA are somehow time-consuming.
> 
> v1 provides the pre-trained models trained at down-sampled DIV2K images. You can obtain those models at [Release](https://github.com/RyanXingQL/PowerQE/releases).
> See also [v1 Instruction](https://github.com/RyanXingQL/PowerQE/tree/ea903fd0d04154c95b321b5100540249856bd44b).

Thanks for instructions! Looking forward to the V2 pretrained models : )
