### ISSUE TITLE
How to avoid "CUDA out of memory" in PyTorch

### ISSUE THREAD

**Issue by wrenchonline** [RyanXingQL/PowerQE#4]
I tried rbqe test Model:
`python ./test.py -opt opts/rbqe.yml -case div2k_jpeg`
`RuntimeError: HIP out of memory. Tried to allocate 5.94 GiB (GPU 0; 7.98 GiB total capacity; 2.25 GiB already allocated; 3.92 GiB free; 4.04 GiB reserved in total by PyTorch)`
Does the hardware configuration required for the test have higher requirements ？How do I modify the GPU memory that has been adapted.

**Comment by RyanXingQL** [comment]
Hi, thanks for using PowerQE!

Since the DIV2K images are so big in resolution (i.e., 2K resolution), it requires a big GPU memory (e.g., up to 20GB GPU memory) for testing.

Besides, RBQE contains rich dense connections, which further require big GPU memory.

For other methods such as CBDNet, up to 10GB memory is also needed.

You may either test small images, or use bigger GPUs.

Otherwise, you may have to change the network structure in the `rbqe.yml`, especially `algorithm -> network -> net`. For examples, you can decrease the `nf_base` and `nlevel`. Note that you may need to train your own network.
